import { sql } from "drizzle-orm";
import {
  integer,
  pgEnum,
  pgTable,
  text,
  timestamp,
  uuid,
} from "drizzle-orm/pg-core";

export const userRole = pgEnum("user_role", ["planner", "venue", "admin"]);

export const users = pgTable("users", {
  // Clerk user ID (e.g. user_2abc...). Not generated by us — assigned by Clerk.
  id: text("id").primaryKey(),
  email: text("email").notNull().unique(),
  role: userRole("role").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
});

export type User = typeof users.$inferSelect;
export type NewUser = typeof users.$inferInsert;

export const propertyStatus = pgEnum("property_status", [
  "pending_approval",
  "approved",
  "rejected",
]);

export const properties = pgTable("properties", {
  id: uuid("id")
    .primaryKey()
    .default(sql`gen_random_uuid()`),
  name: text("name").notNull(),
  city: text("city").notNull(),
  capacity: integer("capacity").notNull(),
  description: text("description"),
  // Nullable: admin-seeded properties have no owner.
  ownerId: text("owner_id").references(() => users.id, {
    onDelete: "set null",
  }),
  status: propertyStatus("status").notNull().default("pending_approval"),
  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
});

export type Property = typeof properties.$inferSelect;
export type NewProperty = typeof properties.$inferInsert;

export const spaces = pgTable("spaces", {
  id: uuid("id")
    .primaryKey()
    .default(sql`gen_random_uuid()`),
  propertyId: uuid("property_id")
    .notNull()
    .references(() => properties.id, { onDelete: "cascade" }),
  name: text("name").notNull(),
  capacity: integer("capacity").notNull(),
  description: text("description"),
  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
});

export type Space = typeof spaces.$inferSelect;
export type NewSpace = typeof spaces.$inferInsert;
